### ISSUE TITLE
Failed to build for `aarch64-linux-android`

### ISSUE THREAD

**Issue by secext2022** [denoland/rusty_v8#1271]
Build command:
```
V8_FROM_SOURCE=1 cargo build -vv --release --target aarch64-linux-android
```

got error:
```
[v8 0.74.1] The current directory is /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/v8-0.74.1
[v8 0.74.1] gn gen --root=/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/v8-0.74.1 /home/runner/work/v8-src/v8-src/target/aarch64-linux-android/release/gn_out
[v8 0.74.1] android/icudtl.dat
[v8 0.74.1] ERROR at //build/android/BUILD.gn:93:17: Could not read file.
[v8 0.74.1]   pydeps_file = "pylib/results/presentation/test_results_presentation.pydeps"
[v8 0.74.1]                 ^------------------------------------------------------------
[v8 0.74.1] I resolved this to "/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/v8-0.74.1/build/android/pylib/results/presentation/test_results_presentation.pydeps".
[v8 0.74.1] See //build/android/BUILD.gn:92:1: whence it was called.
[v8 0.74.1] python_library("test_result_presentations_py") {
[v8 0.74.1] ^-----------------------------------------------
[v8 0.74.1] See //v8/tools/BUILD.gn:39:19: which caused the file to be included.
[v8 0.74.1]     data_deps = [ "//build/android:test_runner_py" ]
[v8 0.74.1]                   ^-------------------------------
[v8 0.74.1] thread 'main' panicked at 'assertion failed: Command::new(gn()).arg(format!(\"--root={}\",\n                                                dirs.root.display())).arg(format!(\"--script-executable={}\",\n                                            python())).arg(\"gen\").arg(&gn_out_dir).arg(\"--args=\".to_owned()\n                                +\n                                &args).stdout(Stdio::inherit()).stderr(Stdio::inherit()).envs(env::vars()).status().expect(\"Coud not run `gn`\").success()', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/v8-0.74.1/build.rs:717:5
[v8 0.74.1] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
The following warnings were emitted during compilation:

warning: Not using sccache or ccache

error: failed to run custom build command for `v8 v0.74.1`

Caused by:
  process didn't exit successfully: `/home/runner/work/v8-src/v8-src/target/release/build/v8-c037bc55a0f012fb/build-script-build` (exit status: 101)
```

It seems that some files is missing at `build/android/pylib`

**Comment by secext2022** [comment]
related issues: #480, #970

**Comment by secext2022** [comment]
To build it, we have to checkout v8 source and copy missing files.
I use this github workflow file to build:

```yml
name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: cargo fetch
    # symlink `v8_src` to rusty_v8
    - run: cargo metadata | node get_v8_path.js

    # FIXME: we have to checkout v8 source, because there is missing files in rusty_v8
    #### start checkout v8 source
    - run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git --single-branch --depth=1
    - run: export PATH=$(pwd)/depot_tools:$PATH && echo $PATH && mkdir v8

    # https://v8.dev/docs/source-code
    - run: export PATH=$(pwd)/depot_tools:$PATH && cd v8 && gclient
    - run: export PATH=$(pwd)/depot_tools:$PATH && cd v8 && fetch v8

    # https://v8.dev/docs/cross-compile-arm
    - run: echo "target_os = ['android']" >> v8/.gclient
    - run: cat v8/.gclient

    - run: export PATH=$(pwd)/depot_tools:$PATH && cd v8 && gclient sync
    #### done checkout v8 source

    # copy missing files
    - run: cp -rn v8/v8/build/android v8_src/build || true

    # build
    - run: cd v8_src && rustup target add aarch64-linux-android
    - run: cd v8_src && V8_FROM_SOURCE=1 cargo build -vv --release --target aarch64-linux-android

    - uses: actions/upload-artifact@v3
      with:
        name: librusty_v8_release_aarch64-linux-android.a
        path: v8_src/target/aarch64-linux-android/release/gn_out/obj/librusty_v8.a
```

and it build ok: <https://github.com/fm-elpac/v8-src/actions/runs/5494783991/jobs/10013772849>
