### ISSUE TITLE
ci: x86_64 build failed on macos-latest image

### ISSUE THREAD

**Issue by Chiichen** [denoland/rusty_v8#1472]
> LGTM, waiting on a build pass.
> 
> @Chiichen It appears that [4e30365](https://github.com/denoland/rusty_v8/pull/1458/commits/4e30365d9ad0a2835d7e697eb19bbc3e5f4ef1de) seems to have caused the apple builds to fail.

Thanks for your reply. It reports in workflow's log at [line 135](https://github.com/denoland/rusty_v8/actions/runs/8803211993/job/24160769631?pr=1458#step:13:136)
```
135 error[E0463]: can't find crate for `core`
```

This looks like a classic error that can occur when we cross-compile without the corresponding tool chain installed. and I found it at [line 57](https://github.com/denoland/rusty_v8/actions/runs/8803211993/job/24160769631?pr=1458#step:13:58)

```
57  Running `CARGO=/Users/runner/.rustup/toolchains/1.76.0-aarch64-apple-darwin/bin/cargo
```

It seems that we are trying to build a x86_64 target on aarch64 platform. I think this may be caused by us not properly installing the Rust toolchain for x86_64-macos on the aarch64-macos device

Actually, I found that the existing workflow does not handle cross-compilation on macos devices. One method is to force it to use x86_64 machines by specifying an older macos version(macos11 or macos12), and the other method is to amend the workflow to support cross-compilation on the macos platform.

_Originally posted by @Chiichen in https://github.com/denoland/rusty_v8/issues/1458#issuecomment-2072854434_

**Comment by Chiichen** [comment]
[here](https://github.com/denoland/rusty_v8/blob/main/.github/workflows/ci.yml#L30) defines the image to be used in ci workflow
```yml
      matrix:
        config:
          - os: macOS-latest
            target: x86_64-apple-darwin
            variant: debug
            cargo: cargo

          - os: macOS-latest
            target: x86_64-apple-darwin
            variant: release
            cargo: cargo
```
However, Macos-latest was added as a mirror in the PR 4 years ago #266. At that time, all github actions used the x86_64 architecture macos as the build mirror. However, today, 4 years later, the macos-latest mirror (that is, macos14) has It may be arm64. The specific image information is given here [runner images](https://github.com/actions/runner-images)
